services:
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    
    environment:
      - FLASK_ENV=production

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    
    depends_on: 
      - api
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - api
      - app

