"""empty message

Revision ID: 90e66b378516
Revises: a127583fb43d
Create Date: 2021-04-19 18:45:50.841352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e66b378516'
down_revision = 'a127583fb43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('o_pid', sa.Integer(), nullable=True))
    op.drop_constraint('orders_item_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['o_pid'], ['pid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_item_fkey', 'orders', 'products', ['item'], ['pid'])
    op.drop_column('orders', 'o_pid')
    # ### end Alembic commands ###
